/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package staffmanagement.GUI;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import staffmanagement.server.RemoteServer;

/**
 *
 * @author penpen
 */
public class EmployeeView extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public EmployeeView() {
        initComponents();
        textVisibility(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameContainer = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        buttonContainer = new javax.swing.JPanel();
        profile = new javax.swing.JButton();
        myShifts = new javax.swing.JButton();
        updatePass = new javax.swing.JButton();
        updateAdd = new javax.swing.JButton();
        updateCon = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDisplay = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gemini Hospital Hatfield");
        setResizable(false);

        frameContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        frameContainer.setPreferredSize(new java.awt.Dimension(555, 433));
        frameContainer.setLayout(new java.awt.BorderLayout());

        heading.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staffmanagement/logo.png"))); // NOI18N
        heading.setText("Gemini Hospital Hatfield");
        frameContainer.add(heading, java.awt.BorderLayout.PAGE_START);

        profile.setBackground(new java.awt.Color(0, 51, 51));
        profile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        profile.setForeground(new java.awt.Color(255, 255, 255));
        profile.setText("My Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });

        myShifts.setBackground(new java.awt.Color(0, 51, 51));
        myShifts.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        myShifts.setForeground(new java.awt.Color(255, 255, 255));
        myShifts.setText("View My Shifts");
        myShifts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myShiftsActionPerformed(evt);
            }
        });

        updatePass.setBackground(new java.awt.Color(0, 51, 51));
        updatePass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updatePass.setForeground(new java.awt.Color(255, 255, 255));
        updatePass.setText("Change Password");
        updatePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePassActionPerformed(evt);
            }
        });

        updateAdd.setBackground(new java.awt.Color(0, 51, 51));
        updateAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateAdd.setForeground(new java.awt.Color(255, 255, 255));
        updateAdd.setText("Update Address");
        updateAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAddActionPerformed(evt);
            }
        });

        updateCon.setBackground(new java.awt.Color(0, 51, 51));
        updateCon.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateCon.setForeground(new java.awt.Color(255, 255, 255));
        updateCon.setText("Update Contact ");
        updateCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateConActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonContainerLayout = new javax.swing.GroupLayout(buttonContainer);
        buttonContainer.setLayout(buttonContainerLayout);
        buttonContainerLayout.setHorizontalGroup(
            buttonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonContainerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(buttonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(updateAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(myShifts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updatePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        buttonContainerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {myShifts, profile, updatePass});

        buttonContainerLayout.setVerticalGroup(
            buttonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonContainerLayout.createSequentialGroup()
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(myShifts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updatePass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateCon)
                .addContainerGap(213, Short.MAX_VALUE))
        );

        buttonContainerLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {myShifts, profile, updatePass});

        frameContainer.add(buttonContainer, java.awt.BorderLayout.LINE_START);

        textDisplay.setColumns(20);
        textDisplay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textDisplay.setRows(5);
        jScrollPane1.setViewportView(textDisplay);

        frameContainer.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(116, 402));

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(0, 51, 51));
        logoutButton.setText("Logut");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 329, Short.MAX_VALUE)
                .addComponent(logoutButton))
        );

        frameContainer.add(jPanel2, java.awt.BorderLayout.LINE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        closeWindow();
        EmployeeLogin log = new EmployeeLogin();
        log.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        try {
            RemoteServer server = (RemoteServer) Naming.lookup("StaffServer");
            textVisibility(true);
            String employeeID = JOptionPane.showInputDialog(this, "Please enter your employee ID");
            textDisplay.setText(server.getProfile(convertStringtoInt(employeeID)));
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_profileActionPerformed

    private void updateAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAddActionPerformed
        try {
            String employeeID;
            String telNo;
            RemoteServer server = (RemoteServer) Naming.lookup("StaffServer");
            employeeID = JOptionPane.showInputDialog(this, "Please enter your employee ID");
            if (employeeID != null) {
                telNo = JOptionPane.showInputDialog(this, "Please enter new address");
                String msg = server.updateAddress(convertStringtoInt(employeeID), telNo);
                JOptionPane.showMessageDialog(this, msg);
            }

        } catch (Exception ex) {
        }
    }//GEN-LAST:event_updateAddActionPerformed

    private void updatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePassActionPerformed
        NewPassword changePassword = new NewPassword();
        changePassword.setVisible(true);

    }//GEN-LAST:event_updatePassActionPerformed

    private void updateConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateConActionPerformed
        try {
            String employeeID;
            String telNo;
            RemoteServer server = (RemoteServer) Naming.lookup("StaffServer");
            employeeID = JOptionPane.showInputDialog(this, "Please enter your employee ID");
            if (employeeID != null) {
                telNo = JOptionPane.showInputDialog(this, "Please enter a new contact number");
                String msg = server.updateContactNo(convertStringtoInt(employeeID), telNo);
                JOptionPane.showMessageDialog(this, msg);
            }

        } catch (Exception ex) {
        }
    }//GEN-LAST:event_updateConActionPerformed

    private void myShiftsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myShiftsActionPerformed
        try {
            String employeeID="";
            textVisibility(true);
            
            RemoteServer server = (RemoteServer) Naming.lookup("StaffServer");
            employeeID = JOptionPane.showInputDialog(this, "Please enter your employee ID");
            textDisplay.setText(server.viewMyShifts(convertStringtoInt(employeeID)));
        } catch (Exception ex) {
           
        }
               

    }//GEN-LAST:event_myShiftsActionPerformed

    private void textVisibility(boolean status) {
        textDisplay.setVisible(status);
    }

    private void closeWindow() {
        WindowEvent close = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(close);
    }

    private int convertStringtoInt(String id) {
        return Integer.parseInt(id);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonContainer;
    private javax.swing.JPanel frameContainer;
    private javax.swing.JLabel heading;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton myShifts;
    private javax.swing.JButton profile;
    private javax.swing.JTextArea textDisplay;
    private javax.swing.JButton updateAdd;
    private javax.swing.JButton updateCon;
    private javax.swing.JButton updatePass;
    // End of variables declaration//GEN-END:variables

}
